-- CLASS MANAGEMENT DATABASE SETUP
-- Run this whole file in Supabase SQL Editor.

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text,
 dob date,
 grade int check(grade between 5 and 11),
 address text,
 school text,
 whatsapp text,
 phone text,
 avatar_url text,
 role text default 'student' check(role in('student','admin')),
 created_at timestamptz default now()
);
create table if not exists public.subjects(id bigint generated by default as identity primary key,name text not null,grade int check(grade between 5 and 11),created_at timestamptz default now());
create table if not exists public.recordings(id bigint generated by default as identity primary key,subject_id bigint references public.subjects(id) on delete cascade,subject_name text,grade int,month text,class_date date,title text,youtube_url text not null,created_at timestamptz default now());
alter table public.recordings add column if not exists is_free boolean not null default false;
create table if not exists public.recording_access(
 id bigint generated by default as identity primary key,
 student_id uuid not null references public.profiles(id) on delete cascade,
 recording_id bigint not null references public.recordings(id) on delete cascade,
 created_at timestamptz default now(),
 unique(student_id,recording_id)
);
create table if not exists public.timetable(id bigint generated by default as identity primary key,subject text,subject_name text,grade int,day text,time text,created_at timestamptz default now());
create table if not exists public.class_fees(id bigint generated by default as identity primary key,grade int,month text,amount numeric(10,2),note text,created_at timestamptz default now());
alter table public.class_fees add column if not exists note text;
-- Subject grade is optional. Existing grade values are kept for compatibility, but the admin form no longer asks for one.
alter table public.subjects alter column grade drop not null;

create table if not exists public.class_grades(
 grade int primary key
);
insert into public.class_grades(grade) values (5),(6),(7),(8),(9),(10),(11) on conflict do nothing;

create table if not exists public.class_months(
 id bigint generated by default as identity primary key,
 name text not null unique,
 created_at timestamptz default now()
);
insert into public.class_months(name) values
('January'),('February'),('March'),('April'),('May'),('June'),('July'),('August'),('September'),('October'),('November'),('December')
on conflict(name) do nothing;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,full_name,dob,grade,address,school,whatsapp,phone)
 values(new.id,new.raw_user_meta_data->>'full_name',nullif(new.raw_user_meta_data->>'dob','')::date,nullif(new.raw_user_meta_data->>'grade','')::int,new.raw_user_meta_data->>'address',new.raw_user_meta_data->>'school',new.raw_user_meta_data->>'whatsapp',new.raw_user_meta_data->>'phone');
 return new;
end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;


-- Optional profile pictures. Registration does not require a photo.
alter table public.profiles add column if not exists avatar_url text;

-- Supabase Storage bucket for optional profile pictures. Public read lets the profile image
-- render in the website; writes are restricted to the authenticated user's own folder.
insert into storage.buckets (id, name, public) values ('avatars','avatars',true)
on conflict (id) do update set public=true;

drop policy if exists avatars_insert on storage.objects;
drop policy if exists avatars_update on storage.objects;
drop policy if exists avatars_delete on storage.objects;
create policy avatars_insert on storage.objects for insert to authenticated
with check (bucket_id='avatars' and name like (auth.uid()::text || '/%'));
create policy avatars_update on storage.objects for update to authenticated
using (bucket_id='avatars' and name like (auth.uid()::text || '/%'))
with check (bucket_id='avatars' and name like (auth.uid()::text || '/%'));
create policy avatars_delete on storage.objects for delete to authenticated
using (bucket_id='avatars' and name like (auth.uid()::text || '/%'));

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.recordings enable row level security;
alter table public.recording_access enable row level security;
alter table public.timetable enable row level security;
alter table public.class_fees enable row level security;
alter table public.class_grades enable row level security;
alter table public.class_months enable row level security;

-- Prevent a normal student from changing admin-controlled identity fields or role.
create or replace function public.protect_profile_fields() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then
    new.full_name := old.full_name;
    new.dob := old.dob;
    new.role := old.role;
    new.id := old.id;
  end if;
  return new;
end;$$;
drop trigger if exists protect_profile_fields on public.profiles;
create trigger protect_profile_fields
before update on public.profiles
for each row execute procedure public.protect_profile_fields();

drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
drop policy if exists subjects_select on public.subjects;
drop policy if exists subjects_insert on public.subjects;
drop policy if exists subjects_update on public.subjects;
drop policy if exists subjects_delete on public.subjects;
drop policy if exists recordings_select on public.recordings;
drop policy if exists recordings_insert on public.recordings;
drop policy if exists recordings_update on public.recordings;
drop policy if exists recordings_delete on public.recordings;
drop policy if exists recording_access_select on public.recording_access;
drop policy if exists recording_access_insert on public.recording_access;
drop policy if exists recording_access_delete on public.recording_access;
drop policy if exists timetable_select on public.timetable;
drop policy if exists timetable_insert on public.timetable;
drop policy if exists timetable_update on public.timetable;
drop policy if exists timetable_delete on public.timetable;
drop policy if exists fees_select on public.class_fees;
drop policy if exists fees_insert on public.class_fees;
drop policy if exists fees_update on public.class_fees;
drop policy if exists fees_delete on public.class_fees;
drop policy if exists grades_select on public.class_grades;
drop policy if exists grades_insert on public.class_grades;
drop policy if exists grades_update on public.class_grades;
drop policy if exists grades_delete on public.class_grades;
drop policy if exists months_select on public.class_months;
drop policy if exists months_insert on public.class_months;
drop policy if exists months_update on public.class_months;
drop policy if exists months_delete on public.class_months;

create policy profiles_select on public.profiles for select to authenticated using(auth.uid()=id or public.is_admin());
create policy profiles_insert on public.profiles for insert to authenticated
with check((auth.uid()=id and role='student') or public.is_admin());
create policy profiles_update on public.profiles for update to authenticated
using(auth.uid()=id or public.is_admin())
with check(auth.uid()=id or public.is_admin());

-- Logged-in students can read class information. Admins can manage it.
create policy subjects_select on public.subjects for select to authenticated using(true);
create policy subjects_insert on public.subjects for insert to authenticated with check(public.is_admin());
create policy subjects_update on public.subjects for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy subjects_delete on public.subjects for delete to authenticated using(public.is_admin());
-- Students can only read Free recordings or recordings explicitly assigned to them.
-- Admins can read all recordings. This is the security boundary; the UI filter alone is not enough.
create policy recordings_select on public.recordings for select to authenticated
using(
  public.is_admin()
  or is_free = true
  or exists (
    select 1 from public.recording_access ra
    where ra.recording_id = recordings.id
      and ra.student_id = auth.uid()
  )
);
create policy recordings_insert on public.recordings for insert to authenticated with check(public.is_admin());
create policy recordings_update on public.recordings for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy recordings_delete on public.recordings for delete to authenticated using(public.is_admin());
create policy recording_access_select on public.recording_access for select to authenticated using(student_id=auth.uid() or public.is_admin());
create policy recording_access_insert on public.recording_access for insert to authenticated with check(public.is_admin());
create policy recording_access_delete on public.recording_access for delete to authenticated using(public.is_admin());

-- Restricted recordings must be assigned explicitly by an admin.
-- Free recordings are visible automatically through recordings_select.
create policy timetable_select on public.timetable for select to authenticated using(true);
create policy timetable_insert on public.timetable for insert to authenticated with check(public.is_admin());
create policy timetable_update on public.timetable for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy timetable_delete on public.timetable for delete to authenticated using(public.is_admin());
create policy fees_select on public.class_fees for select to authenticated using(true);
create policy fees_insert on public.class_fees for insert to authenticated with check(public.is_admin());
create policy fees_update on public.class_fees for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy fees_delete on public.class_fees for delete to authenticated using(public.is_admin());

create policy grades_select on public.class_grades for select to authenticated using(true);
create policy grades_insert on public.class_grades for insert to authenticated with check(public.is_admin());
create policy grades_update on public.class_grades for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy grades_delete on public.class_grades for delete to authenticated using(public.is_admin());

create policy months_select on public.class_months for select to authenticated using(true);
create policy months_insert on public.class_months for insert to authenticated with check(public.is_admin());
create policy months_update on public.class_months for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy months_delete on public.class_months for delete to authenticated using(public.is_admin());

-- Make yourself admin after registering:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='YOUR_ADMIN_EMAIL');
-- IMPORTANT: use the Supabase Publishable/anon key in config.js, never service_role/secret.
